### ISSUE TITLE
import workspace.json file to Watson Conversation tooling not correct

### ISSUE THREAD

**Issue by silencer018** [cdimascio/nationalparks_conversation#2]
I am following the dw learning course to do the chatbot lab 6.  I can successfully import the resources/conversation_workspace.json to Watson Conversation tooling,  but when I go to the tooling to see the dialog, there is no response for the #listparks node, so I always get anything_else node response when I input something like "give a list of parks".  It's different than the course. Is that correct ? It seems the Watson Conversation tooling has been upgraded so it's not compatible with the old workspace.json ?

Thanks!

**Comment by cdimascio** [comment]
@silencer018 do you see #listparks intent as well as examples populated within the intents section of the watson conversation tooling?

**Comment by cdimascio** [comment]
@silencer018 i did a test and it does work for me. i will close this please reopen if you are still having issues
