### ISSUE TITLE
App seems to be broken?

### ISSUE THREAD

**Issue by Blu3b3rry5** [cdimascio/nationalparks_conversation#6]
After cloning and installing on local, when I npm start, the app loads with UI but no "greeting". Also when I type "What parks can you tell me about?" and hit return, nothing appears in app UI and no response either. I have made sure all credentials are correct (username, password, workspace ID, etc).

**Comment by cdimascio** [comment]
@Blu3b3rry5 can you crack open e.g. chrome dev tools and post here any failing request along with the status code and message?
