### ISSUE TITLE
Lab 5: Authentication Problem on Windows

### ISSUE THREAD

**Issue by christophkormesser** [cdimascio/nationalparks_conversation#7]
Hello @cdimascio , I am currently trying to recreate the chatbot, but fail at module 41.

## This is my error:

> { Error: Unauthorized: Access is denied due to invalid credentials.
>   ...
>   code: 401,
>   error: 'Not Authorized',
>   description: '2018-05-25T11:14:24-05:00, Error ERCDPLTFRM-DNLKUPERR occurred when accessing https://gateway.watsonplatform.net/conversation/api/v1/workspaces/%3C86181bd0-cf0e-44a2-8eb5-c80bd2c2d5a1%3E/message?version=2016-09-20, Tran-Id: gateway01-59613562 - Invalid UserId and/or Password. Please confirm that your credentials match the end-point you are trying to access. A common error is trying to use credentials from an experimental or beta release against a GA release or vice versa',
>   body: 'Not Authorized',
>   'x-global-transaction-id': undefined }

I am very certain that I used the right credentials and workspace id. Is there an issue with the url or the new name of watson conversation to watson assistant? (BTW I do not really have any programming skills).

Thanks in advance!

**Comment by cdimascio** [comment]
Are you using Windows?

**Comment by christophkormesser** [comment]
Yes, Windows 10.

**Comment by cdimascio** [comment]
Ok I think it may be an issue with the name of the USERNAME and PASSWORD env vars. I believe those names collide with the windows environment.

One thing you can do is update those vars in .env to something else BM_USERNAME and BM_PASSWORD, then update all calls in the source code from process.env.USERNAME and process.env.PASSWORD to process.env.BM_USERNAME, process.env.BM_PASSWORD

Id this is too complicated, I'll get to it on Tuesday

**Comment by christophkormesser** [comment]
Thank you for the response I'll try it in a few days!

**Comment by christophkormesser** [comment]
So I changed the variables to BM_USERNAME, BM_PASSWORD in the .env file and the index.js but the same error occurred. (also tried changing WORKSPACE_ID to BM_WORKSPACE_ID)

**Comment by cdimascio** [comment]
@christophkormesser im wrong. after viewing the code, i see i was confusing this project with another. all in all, the variables in `.env` should work as expected on Windows. all in all, revert the changes i noted above. apologies for the confusion.

that being, the case, we still dont know why you're experiencing issues. 
once you revert to the original `.env` var names, can you paste that here (with your passwords masked out)
also please supply you node.js and npm version

**Comment by christophkormesser** [comment]
npm version: 
<img width="290" alt="2018-06-11 15_05_10- index js - example - visual studio code" src="https://user-images.githubusercontent.com/39628864/41233185-eda94520-6d88-11e8-8520-a120be7f1a32.png">

node.js:
<img width="397" alt="2018-06-11 15_22_11-node js command prompt" src="https://user-images.githubusercontent.com/39628864/41234011-5008496c-6d8b-11e8-903f-46c988517a9d.png">


.env file:
![inked2018-06-11 14_58_20- env - example - visual studio code_li](https://user-images.githubusercontent.com/39628864/41233098-a1d7bbae-6d88-11e8-8aa4-376fcb4b12cd.jpg)

index.js:
<img width="502" alt="2018-06-11 14_59_31-index js - example - visual studio code" src="https://user-images.githubusercontent.com/39628864/41233115-a7e45c96-6d88-11e8-900d-ad1376bf8e54.png">

**Comment by cdimascio** [comment]
@christophkormesser 
i'm a bit stumped why that is not working for you, given it is essentially just calling the conversation sdk directly. One way to avoid any potential environment and/or `.env` issue is to replace `process.env.USERNAME` and `process.env.PASSWORD` with the actual username and password strings. This is clearly not recommended for a production system, but should be perfectly fine for purposes of the course

Also, with respect to env vars, one more thing to to try... Check the value of the actual environment variable. Any value in the actual environment will override what is in `.env`; You can check with `echo %USERNAME%` and `echo %PASSWORD%`

**Comment by cdimascio** [comment]
The issues occurs on Windows.

I've posted instructions to workaround this issue in the [README](https://github.com/cdimascio/nationalparks_conversation/blob/master/README.md#faq)
